name: Create and publish a Docker image

on:
  push:
    branches: ['feature/dockerize-application']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME}}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          #registry: ${{ env.REGISTRY }}
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build Docker Image
        run: docker build  -t $DOCKER_USERNAME/$REPOSITORY_NAME:${{ steps.date.outputs.date }} .
      
      - name: Push Docker Image to Docker Hub
        run: docker push $DOCKER_USERNAME/$REPOSITORY_NAME:${{ steps.date.outputs.date }}
